/* =============================================================
 * arm_nn_weights.h — SIH26052 AI/ML Tri-Brain Weights
 * Auto-generated by export_edge_ai.py
 * Target: ARM Cortex-M7 / M55 + Ethos-U55 (CMSIS-NN)
 * ============================================================= */

#pragma once
#include <stdint.h>

/* ---- Brain 1: Acoustic Scene Classifier ---- */
/* brain1_fc1_weight: shape=[16, 7], scale=0.004109 */
static const int8_t brain1_fc1_weight[] = {
  1, -97, 57, 29, 118, 17, -5, -29, -54, -50, 58, 79, -22, -47, -103, 91, -11, 62, 56, -83, 83, -125, -71, 117, -109, 69, -34, 49, 22, 113, 11, -29, 55, 50, -102, 35, -12, 93, 126, -98, -112, 62, 37, 13, 60, 107, 91, 27, 114, -56, -84, 78, 79, 103, 36, -18, 20, 53, 127, 106, 117, 92, -55, 72, 96, 42, -100, 62, 93, 115, 94, -1, -102, 23, -97, -94, -117, -120, -6, -99, 108, 24, 80, 67, 0, -95, -95, 61, -101, -43, -43, 1, -24, -2, -16, -52, -59, -111, -24, -88, 8, 46, -5, 114, 78, -87, -21, 104, 94, 10, 21, 94
};
static const float brain1_fc1_weight_scale = 0.004109f;

/* brain1_fc1_bias: shape=[16], scale=0.000141 */
static const int8_t brain1_fc1_bias[] = {
  122, -98, 119, -53, 111, 126, 95, 126, 127, -125, 0, -69, 0, 0, -125, 125
};
static const float brain1_fc1_bias_scale = 0.000141f;

/* brain1_fc2_weight: shape=[5, 16], scale=0.049673 */
static const int8_t brain1_fc2_weight[] = {
  -1, -10, -27, 55, -22, -70, -47, -2, -61, 6, -43, 36, 10, -4, 41, -2, -11, -17, -2, 4, 3, 6, 0, -12, -1, 19, -7, -12, -13, -4, -2, 3, 2, 32, 60, -40, 85, 28, 22, 40, 127, -44, 21, 3, -33, 23, -60, 20, -13, -1, 4, -43, 1, 2, 18, -21, -4, 20, 16, 12, 3, -16, 2, -14, 12, -38, -100, 3, 10, -15, -9, 2, 28, 48, -17, -57, -18, 1, 37, -10
};
static const float brain1_fc2_weight_scale = 0.049673f;

/* brain1_fc2_bias: shape=[5], scale=0.039229 */
static const int8_t brain1_fc2_bias[] = {
  51, 25, -127, 15, -20
};
static const float brain1_fc2_bias_scale = 0.039229f;

/* ---- Brain 2: Neural Step-Size Supervisor ---- */
/* brain2_fc1_weight: shape=[6, 8], scale=0.015763 */
static const int8_t brain2_fc1_weight[] = {
  76, -58, 24, -96, 50, -39, 31, -20, -38, 115, -75, 45, 84, 26, -50, 39, 57, -32, 88, -51, 18, 57, 12, -44, -127, 39, 103, 26, -43, 70, -24, 58, 26, 69, -39, 113, -77, -32, 62, -52, 89, -75, 33, 64, 58, -63, 39, 26
};
static const float brain2_fc1_weight_scale = 0.015763f;

/* brain2_fc1_bias: shape=[6], scale=0.004043 */
static const int8_t brain2_fc1_bias[] = {
  45, -71, 35, 127, -51, 90
};
static const float brain2_fc1_bias_scale = 0.004043f;

/* brain2_fc2_weight: shape=[2, 6], scale=0.011669 */
static const int8_t brain2_fc2_weight[] = {
  93, -70, 59, -121, 84, -44, -58, 110, -76, 67, -50, 127
};
static const float brain2_fc2_weight_scale = 0.011669f;

/* brain2_fc2_bias: shape=[2], scale=0.020331 */
static const int8_t brain2_fc2_bias[] = {
  44, 127
};
static const float brain2_fc2_bias_scale = 0.020331f;

/* ---- Brain 3: Deep Spectral Mask Network ---- */
/* brain3_net_0_weight: shape=[16, 10], scale=0.003121 */
static const int8_t brain3_net_0_weight[] = {
  -56, -121, -110, 81, 102, -54, 95, -105, -86, 16, 68, 26, -52, 48, -120, 53, -114, -94, 17, 45, -76, -25, 89, 112, -8, 31, 10, -115, 94, -46, 64, -92, -96, 115, -4, -64, 76, 109, 59, -1, -31, -115, 6, 52, -93, -59, 77, 99, 6, -16, 48, -87, -60, -51, 66, 124, -26, 4, 88, -26, 69, -19, 94, -105, 9, 117, 97, 5, 27, 6, 10, -77, -2, 99, -48, 24, -41, 67, 102, 84, -95, -114, 107, -36, -96, -104, -17, 60, 64, 55, 98, 34, 78, -99, -101, 127, 60, -79, -6, -94, -126, 23, 21, 33, 112, -84, -86, 70, -4, -47, 116, -76, -51, -106, -28, 13, 70, -83, 87, 112, 83, -44, -66, 30, 27, 54, -40, -111, 73, 91, -27, -4, 4, 105, -21, -91, -106, -5, 104, -83, 5, -81, 53, 95, 120, 70, 62, -29, -115, 83, -20, -70, 0, -17, -96, -96, -91, 93, -74, 41
};
static const float brain3_net_0_weight_scale = 0.003121f;

/* brain3_net_0_bias: shape=[16], scale=0.000928 */
static const int8_t brain3_net_0_bias[] = {
  90, 89, 89, 89, 127, 127, 89, 127, 89, 126, 89, 91, 89, 89, 126, 115
};
static const float brain3_net_0_bias_scale = 0.000928f;

/* brain3_net_2_weight: shape=[8, 16], scale=0.003014 */
static const int8_t brain3_net_2_weight[] = {
  -91, 35, -29, 24, -57, -81, 36, 74, 126, -106, 103, -62, 22, -13, -20, -102, -67, 83, -15, -28, 10, 95, -47, 58, 122, -71, -94, -86, 120, 48, -16, 75, -126, 58, 118, 0, -59, -6, -82, -127, 2, -95, 89, 1, 45, 103, 81, 84, -36, -104, 53, -71, 112, -93, 56, -38, -26, 72, -115, -29, -116, 50, -4, -57, -87, -7, -19, -103, 18, -66, -75, -125, 11, 89, 69, 95, -14, 99, 11, 112, 88, 94, 35, 30, -105, -19, 125, -51, 20, -99, 121, -31, 125, 84, -90, 51, -106, -22, -60, -45, -47, -7, -95, -29, -66, 1, 97, -98, -55, -12, -116, 93, 69, 95, -93, 127, 121, -31, -22, -13, -32, 97, 113, 41, -106, -90, -26, -102
};
static const float brain3_net_2_weight_scale = 0.003014f;

/* brain3_net_2_bias: shape=[8], scale=0.000926 */
static const int8_t brain3_net_2_bias[] = {
  89, 127, 89, 124, 90, 89, 89, 89
};
static const float brain3_net_2_bias_scale = 0.000926f;

/* brain3_net_4_weight: shape=[1, 8], scale=0.004753 */
static const int8_t brain3_net_4_weight[] = {
  86, -70, 110, -18, 105, 127, 31, 111
};
static const float brain3_net_4_weight_scale = 0.004753f;

/* brain3_net_4_bias: shape=[1], scale=0.000649 */
static const int8_t brain3_net_4_bias[] = {
  127
};
static const float brain3_net_4_bias_scale = 0.000649f;
