"""
export_edge_ai.py — Export Trained Models to Edge Formats
SIH26052 Tactical ANC Headset — AI/ML Tri-Brain Engine

Exports the trained TriBrainANCEngine to:
    1. Quantised INT8 C header  (arm_nn_weights.h) — for ARM Cortex-M7 / M55 + CMSIS-NN
    2. Embedded JavaScript      (aiml_weights.js)  — for in-browser execution
    3. ONNX model               (model.onnx)       — for deployment pipeline

Usage:
    pip install torch numpy onnx
    python export_edge_ai.py --checkpoint model.pt --out-dir ./export
"""

import argparse
import math
import os
import struct
import numpy as np
import torch

from neural_anc_model import (
    TriBrainANCEngine, N_CLASSES, N_FEATURES, N_MELS, FFT_N,
    AcousticSceneClassifier, NeuralStepSupervisor, DeepSpectralMaskNet,
)


# ---------------------------------------------------------------------------
# INT8 Quantisation helpers
# ---------------------------------------------------------------------------

def quantise_int8(tensor: torch.Tensor):
    """Symmetric per-tensor INT8 quantisation. Returns (int8_array, scale)."""
    t     = tensor.detach().float()
    scale = t.abs().max().item() / 127.0 + 1e-8
    q     = (t / scale).round().clamp(-127, 127).to(torch.int8)
    return q.numpy(), scale


# ---------------------------------------------------------------------------
# C header export (arm_nn_weights.h)
# ---------------------------------------------------------------------------

def to_c_array(name: str, data: np.ndarray, scale: float, dtype: str = "int8_t") -> str:
    flat  = data.flatten()
    vals  = ", ".join(str(int(v)) for v in flat)
    lines = [
        f"/* {name}: shape={list(data.shape)}, scale={scale:.6f} */",
        f"static const {dtype} {name}[] = {{",
        f"  {vals}",
        f"}};",
        f"static const float {name}_scale = {scale:.6f}f;",
        "",
    ]
    return "\n".join(lines)


def export_c_header(model: TriBrainANCEngine, path: str):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)

    sections = [
        "/* =============================================================\n"
        " * arm_nn_weights.h — SIH26052 AI/ML Tri-Brain Weights\n"
        " * Auto-generated by export_edge_ai.py\n"
        " * Target: ARM Cortex-M7 / M55 + Ethos-U55 (CMSIS-NN)\n"
        " * ============================================================= */\n",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]

    # Brain 1 — classifier
    sections.append("/* ---- Brain 1: Acoustic Scene Classifier ---- */")
    for name, param in model.brain1.named_parameters():
        safe = "brain1_" + name.replace('.', '_')
        q, scale = quantise_int8(param)
        sections.append(to_c_array(safe, q, scale))

    # Brain 2 — step-size MLP
    sections.append("/* ---- Brain 2: Neural Step-Size Supervisor ---- */")
    for name, param in model.brain2.named_parameters():
        safe = "brain2_" + name.replace('.', '_')
        q, scale = quantise_int8(param)
        sections.append(to_c_array(safe, q, scale))

    # Brain 3 — spectral mask net
    sections.append("/* ---- Brain 3: Deep Spectral Mask Network ---- */")
    for name, param in model.brain3.named_parameters():
        safe = "brain3_" + name.replace('.', '_')
        q, scale = quantise_int8(param)
        sections.append(to_c_array(safe, q, scale))

    with open(path, 'w') as f:
        f.write("\n".join(sections))
    print(f"[export] C header written: {path}")


# ---------------------------------------------------------------------------
# JavaScript weights export (aiml_weights.js)
# ---------------------------------------------------------------------------

def export_js_weights(model: TriBrainANCEngine, path: str):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    lines = [
        "/* aiml_weights.js — Pre-trained weights for aiml_engine.js",
        " * Auto-generated by export_edge_ai.py — do not edit by hand.",
        " * Load this file BEFORE aiml_engine.js to override hand-tuned weights. */",
        "",
        "// Brain 1 Classifier weights",
    ]
    for name, param in model.brain1.named_parameters():
        arr  = param.detach().numpy().flatten().tolist()
        vals = "[" + ", ".join(f"{v:.5f}" for v in arr) + "]"
        safe = "AIML_BRAIN1_" + name.replace('.', '_').upper()
        lines.append(f"const {safe} = {vals};")

    lines.append("\n// Brain 2 Step-Size MLP weights")
    for name, param in model.brain2.named_parameters():
        arr  = param.detach().numpy().flatten().tolist()
        vals = "[" + ", ".join(f"{v:.5f}" for v in arr) + "]"
        safe = "AIML_BRAIN2_" + name.replace('.', '_').upper()
        lines.append(f"const {safe} = {vals};")

    lines.append("\n// Brain 3 Spectral Mask weights")
    for name, param in model.brain3.named_parameters():
        arr  = param.detach().numpy().flatten().tolist()
        vals = "[" + ", ".join(f"{v:.5f}" for v in arr) + "]"
        safe = "AIML_BRAIN3_" + name.replace('.', '_').upper()
        lines.append(f"const {safe} = {vals};")

    with open(path, 'w') as f:
        f.write("\n".join(lines))
    print(f"[export] JS weights written: {path}")


# ---------------------------------------------------------------------------
# ONNX export
# ---------------------------------------------------------------------------

def export_onnx(model: TriBrainANCEngine, path: str):
    try:
        import onnx
    except ImportError:
        print("[export] onnx not installed — skipping ONNX export. pip install onnx")
        return

    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    model.eval()
    feat_dummy = torch.randn(1, N_FEATURES)
    mode_dummy = torch.zeros(1, dtype=torch.long)

    torch.onnx.export(
        model,
        (feat_dummy, mode_dummy),
        path,
        export_params   = True,
        opset_version   = 17,
        dynamo          = False,
        input_names     = ["features", "mode"],
        output_names    = ["class_probs", "step_params", "spectral_mask"],
        dynamic_axes    = {
            "features"     : {0: "batch"},
            "mode"         : {0: "batch"},
            "class_probs"  : {0: "batch"},
            "step_params"  : {0: "batch"},
            "spectral_mask": {0: "batch"},
        },
    )
    print(f"[export] ONNX model written: {path}")


# ---------------------------------------------------------------------------
# Quantisation accuracy check
# ---------------------------------------------------------------------------

def check_quantisation_accuracy(model: TriBrainANCEngine):
    print("\n[check] Quantisation accuracy (FP32 vs INT8)")
    for name, param in model.named_parameters():
        t       = param.detach().float()
        q, sc   = quantise_int8(param)
        t_rec   = torch.from_numpy(q.astype(np.float32)) * sc
        mse     = ((t.flatten() - t_rec.flatten()) ** 2).mean().item()
        signal_pow = max(1e-12, t.pow(2).mean().item())
        snr_db     = 10 * math.log10(signal_pow / (mse + 1e-12))
        status     = "OK" if snr_db > 30 else "LOW"
        print(f"  [{status}] {name:<40} SNR={snr_db:.1f} dB")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export SIH26052 AI/ML models to edge formats")
    parser.add_argument("--checkpoint", type=str, default="model.pt",
                        help="Path to trained model.pt checkpoint")
    parser.add_argument("--out-dir",    type=str, default="export",
                        help="Output directory")
    args = parser.parse_args()

    # Load or create model
    model = TriBrainANCEngine()
    if os.path.exists(args.checkpoint):
        model.load_state_dict(torch.load(args.checkpoint, map_location='cpu'))
        print(f"[export] Loaded checkpoint: {args.checkpoint}")
    else:
        print(f"[export] No checkpoint found at '{args.checkpoint}' — using hand-tuned weights")

    model.eval()

    # Export
    export_c_header  (model, os.path.join(args.out_dir, "arm_nn_weights.h"))
    export_js_weights(model, os.path.join(args.out_dir, "aiml_weights.js"))
    export_onnx      (model, os.path.join(args.out_dir, "model.onnx"))
    check_quantisation_accuracy(model)

    print("\n[export] All exports complete.")
    print(f"  C header   -> {args.out_dir}/arm_nn_weights.h  (include in Cortex-M7 project)")
    print(f"  JS weights  -> {args.out_dir}/aiml_weights.js   (load before aiml_engine.js)")
    print(f"  ONNX model  -> {args.out_dir}/model.onnx        (deployment pipeline)")
